name: Deploy Web to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ speakify ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare public folder
        run: |
          mkdir -p public
          cp -a index.html main.js manifest.webmanifest sw.js public/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages